import { test, expect } from '@playwright/test';

test('createNewReceiving', async ({ page }) => {
  await page.getByRole('link', { name: 'Receiving', exact: true }).click();
  await page.getByRole('button', { name: 'Create New Receiving' }).click();
  await page.locator('div').filter({ hasText: /^\*Receiving TypePO$/ }).locator('svg').click();
  await page.locator('#react-select-115-option-0').click();
  await page.getByPlaceholder('Identifier').click();
  await page.getByPlaceholder('Identifier').click();
  await page.getByPlaceholder('Identifier').click();
  await page.getByPlaceholder('Identifier').click();
  await page.getByPlaceholder('Identifier').click();
  await page.getByPlaceholder('Identifier').fill('1');
  await page.getByText('*Identifier').click();
  await page.getByPlaceholder('Supplier').click();
  await page.getByPlaceholder('Supplier').fill('RBTestsupplier');
  await page.getByPlaceholder('Courier').click();
  await page.getByPlaceholder('Courier').fill('TestCourier');
  await page.getByPlaceholder('Tracking number').click();
  await page.getByPlaceholder('Tracking number').fill('trackingnumbertest');
  await page.getByPlaceholder('Description').click();
  await page.getByPlaceholder('Description').fill('FirstItemPOTest');
  await page.getByPlaceholder('Quantity to Receive').click();
  await page.getByPlaceholder('Quantity to Receive').fill('1');
  await page.getByPlaceholder('Quantity Received').click();
  await page.getByPlaceholder('Quantity Received').fill('1');
  await page.getByText('*Description*Quantity to Receive*Quantity ReceivedAdd a new line').click();
  await page.getByRole('button', { name: 'Add a new line' }).click();
  await page.locator('input[name="receivingItemsDtoList\\.1\\.description"]').click();
  await page.locator('input[name="receivingItemsDtoList\\.1\\.description"]').fill('secondItemPOTest');
  await page.locator('input[name="receivingItemsDtoList\\.1\\.quantityToReceive"]').click();
  await page.locator('input[name="receivingItemsDtoList\\.1\\.quantityToReceive"]').fill('1');
  await page.locator('input[name="receivingItemsDtoList\\.1\\.quantity"]').click();
  await page.locator('input[name="receivingItemsDtoList\\.1\\.quantity"]').fill('1');
  await page.getByRole('tab', { name: 'Fully Received' }).click();
  await page.getByPlaceholder('Note').click();
  await page.getByPlaceholder('Note').fill('test of a receiving');
  await page.getByRole('button', { name: 'Save' }).click();
});